BeezMart/Areas/CRM/Controllers/OrgFlagsController.cs
using BeezMart.Entities.CRM;
using BeezMart.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BeezMart.Areas.CRM.Controllers;

[Area("CRM")]
[Authorize(Roles = BeezMart.Security.UserRoles.UserForCRM)]
public class OrgFlagsController : Controller
{

    public ViewComponentResult _List(int OrganizationID)
    {
        return ViewComponent(typeof(BeezMart.Areas.CRM.ViewComponents.OrgContacts.List), new { OrganizationID = OrganizationID });
    }

    [HttpGet]
    public ViewComponentResult _Edit(int OrganizationID, long? FlagID)
    {
        return ViewComponent(typeof(BeezMart.Areas.CRM.ViewComponents.OrgContacts.Edit), new { OrganizationID = OrganizationID, FlagID = FlagID });
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<PartialViewResult> _Edit(OrgFlagModel orgFlag)
    {
        List<OrgFlagModel> viewModel;
        if (!Request.Form.ContainsKey("FieldID") || string.IsNullOrEmpty(Request.Form["FieldID"][0]))
        {
            AppMessage msg = new AppMessage();
            msg.AppendMessage("Please select the type of organization flag you want added!");
            ViewBag.AppMessage = msg.ToHtmlError();
            viewModel = await BeezMart.DAL.CRM.OrgFlags.ListAsync(orgFlag.OrganizationID);
            return PartialView("_List", viewModel);
        }
        if (ModelState.IsValid)
        {
            await BeezMart.DAL.CRM.OrgFlags.SaveAsync(orgFlag);
        }
        else
        {
            AppMessage msg = new AppMessage();
            msg.AppendMessage("You have submitted an invalid or incomplete organization flag. Please check and try again.");
            ViewBag.AppMessage = msg.ToHtmlError();
        }
        viewModel = await BeezMart.DAL.CRM.OrgFlags.ListAsync(orgFlag.OrganizationID);
        return PartialView("_List", viewModel);
    }

    [HttpDelete]
    [ValidateAntiForgeryToken]
    public async Task<PartialViewResult> _Delete(int OrganizationID, long RecordID)
    {
        await BeezMart.DAL.CRM.OrgFlags.DeleteAsync(RecordID);
        List<OrgFlagModel> viewModel = await BeezMart.DAL.CRM.OrgFlags.ListAsync(OrganizationID);
        return PartialView("_List", viewModel);
    }
}

BeezMart/Areas/CRM/Views/OrgFlags/_Edit.cshtml
@using BeezMart.Caching.CRM
@model OrgFlagModel
@{
	if (Model == null) throw new NullReferenceException("ViewModel is null.");
	List<OrgFieldModel> flagTypes = await OrgFlags.GetFlagTypesAsync();
	List<string> categories = await OrgFlags.GetCategoriesAsync();
}
@Html.Raw(ViewBag.AppMessage)
<aside id="ModalEditFlag" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" data-bs-backdrop="static">
	<div class="modal-dialog">
		<div class="modal-content">
			<form asp-action="_Edit" asp-controller="OrgFlags" method="post" id="frmFlagDetail">
				<header class="modal-header">
					<h4 class="modal-title">Flag detail</h4>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</header>
				<section class="modal-body">
					<input type="hidden" name="ID" />
					<input type="hidden" name="OrganizationID" value="@Model.OrganizationID" />
					<div class="mb-3">
						<label for="ddlFlagCategory" class="Required">Category</label>
						<select id="ddlFlagCategory" onchange="javascript: ddlCategory_Change(this, 'FlagList');" class="form-control">
							<option selected="selected">=== FLAGS WITH NO CATEGORY ===</option>
							@foreach (string category in categories)
							{
								<option>@category</option>
							}
						</select>
					</div>
					<div class="mb-3">
						<p>Please select the flag you want to add</p>
						<ul id="FlagList">
							@foreach (OrgFieldModel flagType in flagTypes)
							{
								<li data-val-category="@flagType.Category"><label><input type="radio" name="FieldID" value="@flagType.ID" /> @flagType.Name</label></li>
							}
						</ul>
					</div>
					<div class="mb-3">
						<label for="txtFlagComments">Comments</label>
						<textarea id="txtFlagComments" name="Comments" rows="5" maxlength="256" class="form-control">@Model.Comments</textarea>
					</div>
				</section>
				<footer class="modal-footer">
					<button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button>
					<button type="submit" class="btn btn-primary">Save flag</button>
				</footer>
			</form>
		</div>
	</div>
</aside>

BeezMart/Areas/CRM/Views/OrgFlags/_List.cshtml
@model List<OrgFlagModel>
@{
	if (Model == null) throw new NullReferenceException("ViewModel is null.");
}
@Html.Raw(ViewBag.AppMessage)
<table class="table table-hover table-sm">
	<thead>
		<tr>
			<th colspan="3">Flags</th>
		</tr>
	</thead>
	<tbody>
		@foreach (OrgFlagModel flag in Model) {
			<tr data-record="@flag.ID" data-type="@flag.FieldID">
				<td>@flag.Category</td>
				<td title="@flag.Comments"><a>@flag.Name</a></td>
				<td><a>&times;</a></td>
			</tr>
		}
	</tbody>
	<tfoot>
		<tr>
			<td colspan="3"><button type="button" class="btn btn-outline-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#ModalEditFlag">Add new</button></td>
		</tr>
	</tfoot>
</table>