BeezMart/Areas/Archiving/ViewModels/DocLinks.cs
using BeezMart.Entities;
using BeezMart.Entities.Archiving;
using BeezMart.Entities.Billing;
using BeezMart.Entities.CRM;
using BeezMart.Entities.TimeSheet;

namespace BeezMart.Areas.Archiving.ViewModels.DocLinks;

public class Link_Params
{
	public long DocumentID { get; set; }
	public EntityType EntityType { get; set; }
	public string[]? EntityReferences { get; set; }
	public string? ReturnUrl { get; set; }
}
public class LinkOrganizations_ViewModel
{
    public string? Name { get; set; }
	public bool Exact { get; set; }			// NameExactMatching
	public List<byte>? Segments { get; set; }
	public List<short>? Flags { get; set; }
	public string? Contact { get; set; }
	public string? City { get; set; }
    public EntityType EntityType { get; } = EntityType.CrmOrganization;
    public DocumentModel? Document { get; set; }
}
public class _LinkOrganizations_Params
{
    public string? Name { get; set; }
    public bool NameExactMatching { get; set; }
    public string? Contact { get; set; }
    public string? City { get; set; }
    public List<short>? Flags { get; set; }
    public List<byte>? Segments { get; set; }
}
public class LinkPersons_ViewModel
{
    public string? Name { get; set; }
	public bool Exact { get; set; }			// NameExactMatching
	public List<byte>? Segments { get; set; }
	public List<short>? Flags { get; set; }
	public string? Contact { get; set; }
	public string? City { get; set; }
    public EntityType EntityType { get; } = EntityType.CrmPerson;
    public DocumentModel? Document { get; set; }
}
public class _LinkPersons_Params
{
    public string? Name { get; set; }
    public bool NameExactMatching { get; set; }
    public string? Contact { get; set; }
    public string? City { get; set; }
    public List<short>? Flags { get; set; }
    public List<byte>? Segments { get; set; }
}
public class LinkInvoices_ViewModel
{
    public string? Customer { get; set; }
    public int? OrganizationID { get; set; }
    public int? PersonID { get; set; }
    public bool Exact { get; set; }
	public DateTime? After { get; set; }
	public DateTime? Before { get; set; }
	public string? IDs { get; set; }
	public string? AccIDs { get; set; }					// Accounting IDs
	public string? Curr { get; set; }					// Currency
	public InvoiceStatus? Status { get; set; }			// Status
    public bool Overdue { get; set; }
    public EntityType EntityType { get; } = EntityType.BillingInvoice;
    public DocumentModel? Document { get; set; }
}
public class _LinkInvoices_Params
{
    public string? Customer { get; set; }
    public int? OrganizationID { get; set; }
    public int? PersonID { get; set; }
    public bool Exact { get; set; }
    public DateTime? After { get; set; }
    public DateTime? Before { get; set; }
    public string? IDs { get; set; }
    public string? AccIDs { get; set; }                  // Accounting IDs
    public string? Curr { get; set; }                    // Currency
    public InvoiceStatus? Status { get; set; }			// Status
    public bool Overdue { get; set; }
}
public class LinkProjects_ViewModel
{
    public string? Title { get; set; }
    public string? Customer { get; set; }
    public int? OrganizationID { get; set; }
    public int? PersonID { get; set; }
    public bool Exact { get; set; }
	public DateTime? After { get; set; }
	public DateTime? Before { get; set; }
    public string? IDs { get; set; }
    public string? PM { get; set; }
    public short? Categ { get; set; }
    public ProjectStatus? Status { get; set; }
    public EntityType EntityType { get; } = EntityType.SalesProject;
    public DocumentModel? Document { get; set; }
}
public class _LinkProjects_Params
{
    public string? Title { get; set; }
    public string? Customer { get; set; }
    public int? OrganizationID { get; set; }
    public int? PersonID { get; set; }
    public bool Exact { get; set; }
    public DateTime? After { get; set; }
    public DateTime? Before { get; set; }
    public string? IDs { get; set; }
    public string? PM { get; set; }
    public short? Categ { get; set; }
    public ProjectStatus? Status { get; set; }
}
public class LinkActivities_ViewModel
{
    public string? Title { get; set; }
    public bool Exact { get; set; }
    public string? Customer { get; set; }
    public string? Prj { get; set; }
    public int? OrganizationID { get; set; }
    public int? PersonID { get; set; }
	public DateTime? After { get; set; }
	public DateTime? Before { get; set; }
    public string? IDs { get; set; }
    public short? Categ { get; set; }
    public ProjectStatus? Status { get; set; }
    public EntityType EntityType { get; } = EntityType.SalesActivity;
    public DocumentModel? Document { get; set; }
}
public class _LinkActivities_Params
{
    public string? Title { get; set; }
    public bool Exact { get; set; }
    public string? Customer { get; set; }
    public string? Prj { get; set; }
    public int? OrganizationID { get; set; }
    public int? PersonID { get; set; }
    public DateTime? After { get; set; }
    public DateTime? Before { get; set; }
    public string? IDs { get; set; }
    public short? Categ { get; set; }
    public ProjectStatus? Status { get; set; }
}
public class LinkDocuments_ViewModel
{
    public EntityType EntityType { get; set; }
    public string? EntityReference { get; set; }
    public OrganizationModel? Organization { get; set; }
    public PersonModel? Person { get; set; }
    public InvoiceModel? Invoice { get; set; }
    public ProjectModel? Project { get; set; }
    public ActivityModel? Activity { get; set; }
    public string? IDs { get; set; }
    public string? Title { get; set; }
    public bool Exact { get; set; } = false;
    public short? Categ { get; set; } = null;
    public DocumentStatus? Status { get; set; }
    public string? ExtUrl { get; set; }
    public string? ExtID { get; set; }
    public DateTime? Start { get; set; } = null;
    public DateTime? End { get; set; } = null;
    public List<DocumentModel>? Documents { get; set; }
}

BeezMart/Areas/Billing/Controllers/InvoicesController.cs
using BeezMart.Entities.Billing;
using BeezMart.Areas.Billing.ViewModels.Invoices;
using BeezMart.Utils;
using HtmlAgilityPack;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using System.Drawing;
using System.Globalization;
using System.Text;

namespace BeezMart.Areas.Billing.Controllers;

[Area("Billing")]
[Authorize(Roles = BeezMart.Security.UserRoles.UserForFinance)]
public class InvoicesController : Controller
{
	protected static string _limitedDefaultLookupResult = "No search criteria is specified. Only the latest {0} invoice records will show up at most.";

	public ActionResult Index()
	{
		return View();
	}

	public async Task<PartialViewResult> _Start(string SearchString)
	{
		if (string.IsNullOrWhiteSpace(SearchString))
		{
            AppMessage msg = new AppMessage();
            msg.AppendMessage("Please specify a search string to attempt finding existing invoicing details in the system");
            ViewBag.AppMessage = msg.ToHtmlWarning();
			return PartialView("_Message");
		}
        Start_ViewModel viewModel = new Start_ViewModel();
        await viewModel.LookupOrganizations(SearchString, maxRecords: 10);
        await viewModel.LookupPersons(SearchString, maxRecords: 10);
        await viewModel.LookupCustomerSavedSettings(SearchString, maxRecords: 10);
        await viewModel.LookupInvoices(SearchString, maxRecords: 10);
        return PartialView(viewModel);
	}
	[HttpGet]
	public ViewResult Start()
	{
		// use for adding an invoice starting from a customer, sales order or delivery document
		return View();
	}
	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<ActionResult> Start(CustomerBillingDetailsModel billingDetails)
	{
		Add_ViewModel viewModel = new Add_ViewModel { };
        viewModel.BillingAddressID = billingDetails.BillingAddressID;
        viewModel.BankAccountID = billingDetails.BankAccountID;
		viewModel.Invoice = new InvoiceModel {
                OrganizationID = billingDetails.OrganizationID,
                PersonID = billingDetails.PersonID,
                CustomerName = billingDetails.CustomerName,
                CustomerCity = billingDetails.City,
                CustomerProvince = billingDetails.StateProvince,
                CustomerAddress = billingDetails.StreetAddress1,
                CustomerRegistrationNumber = billingDetails.RegistrationNumber,
                CustomerTaxID = billingDetails.TaxID,
                CustomerBankName = billingDetails.BankName,
                CustomerBankAccount = billingDetails.BankAccountIBAN,
            };
		viewModel.Invoice.Currency = MyApp.ConfigSettings["Billing.Default-Currency"];
		viewModel.Invoice.VATpercentage = decimal.Parse(MyApp.ConfigSettings["Billing.Default-VAT-Percentage"]);
		viewModel.Invoice.IssueDate = DateTime.Now;
		viewModel.Invoice.DueDate = DateTime.Now.AddDays(int.Parse(MyApp.ConfigSettings["Billing.Default-Payment-Allowance-In-Days"]));
		viewModel.Invoice.Type = InvoiceType.Regular;
		viewModel.HandoverDelegates = await BeezMart.DAL.Billing.HandoverDelegates.ListAsync();
		viewModel.HandoverTransports = await BeezMart.DAL.Billing.HandoverTransports.ListAsync();
		#region auto-populate fields with previously set cookies
		if (Request.Cookies.ContainsKey("Billing.Invoice.Exchange-Rate"))
		{
			viewModel.Invoice.Detail1 = Request.Cookies["Billing.Invoice.Exchange-Rate"];
			DateTime lastUpdated = DateTime.Now;
			if (Request.Cookies.ContainsKey("Billing.Invoice.Exchange-Rate-Date"))
			{
				string? tmp = Request.Cookies["Billing.Invoice.Exchange-Rate-Date"];
				if (DateTime.TryParseExact(tmp, "yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture, DateTimeStyles.None, out lastUpdated))
					viewModel.ExchangeRateDate = lastUpdated;
			}
		}
		if (Request.Cookies.ContainsKey("Billing.Invoice.Operator-Details"))
		{
			viewModel.Invoice.Detail2 = Request.Cookies["Billing.Invoice.Operator-Details"];
		}
		if (Request.Cookies.ContainsKey("Billing.Invoice.Comments"))
		{
			viewModel.Invoice.Detail3 = Request.Cookies["Billing.Invoice.Comments"];
		}
		#endregion
		return View("Add", viewModel);
	}

	[HttpGet]
	public async Task<ViewResult> Add()
	{
		Add_ViewModel viewModel = new Add_ViewModel();
		viewModel.Invoice = new InvoiceModel();
		viewModel.Invoice.Currency = MyApp.ConfigSettings["Billing.Default-Currency"];
		viewModel.Invoice.VATpercentage = decimal.Parse(MyApp.ConfigSettings["Billing.Default-VAT-Percentage"], CultureInfo.CurrentUICulture);
		viewModel.Invoice.IssueDate = DateTime.Now;
		viewModel.Invoice.DueDate = DateTime.Now.AddDays(int.Parse(MyApp.ConfigSettings["Billing.Default-Payment-Allowance-In-Days"]));
		viewModel.Invoice.Type = InvoiceType.Regular;
		viewModel.HandoverDelegates = await BeezMart.DAL.Billing.HandoverDelegates.ListAsync();
		viewModel.HandoverTransports = await BeezMart.DAL.Billing.HandoverTransports.ListAsync();
		#region auto-populate fields with previously set cookies
		if (Request.Cookies.ContainsKey("Billing.Invoice.Exchange-Rate"))
		{
			viewModel.Invoice.Detail1 = Request.Cookies["Billing.Invoice.Exchange-Rate"];
			DateTime lastUpdated = DateTime.Now;
			if (Request.Cookies.ContainsKey("Billing.Invoice.Exchange-Rate-Date"))
			{
				string? tmp = Request.Cookies["Billing.Invoice.Exchange-Rate-Date"];
				if (DateTime.TryParseExact(tmp, "yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture, DateTimeStyles.None, out lastUpdated))
					viewModel.ExchangeRateDate = lastUpdated;
			}
		}
		if (Request.Cookies.ContainsKey("Billing.Invoice.Operator-Details"))
		{
			viewModel.Invoice.Detail2 = Request.Cookies["Billing.Invoice.Operator-Details"];
		}
		if (Request.Cookies.ContainsKey("Billing.Invoice.Comments"))
		{
			viewModel.Invoice.Detail3 = Request.Cookies["Billing.Invoice.Comments"];
		}
		#endregion
		return View(viewModel);
	}
	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<ActionResult> Add(Add_ViewModel viewModel)
	{
		TryValidateModel(viewModel);
		if (ModelState.IsValid)
		{
			#region save some fields into cookies for future use
			CookieOptions cookieOptions = new CookieOptions() { Expires = DateTime.Now.AddYears(1) };
			if (Request.Cookies.ContainsKey("Billing.Invoice.Exchange-Rate"))
			{
				if (viewModel.Invoice?.Detail1 != Request.Cookies["Billing.Invoice.Exchange-Rate"])
				{
                    if (string.IsNullOrWhiteSpace(viewModel.Invoice?.Detail1)) Response.Cookies.Delete("Billing.Invoice.Exchange-Rate");
					else Response.Cookies.Append("Billing.Invoice.Exchange-Rate", viewModel.Invoice.Detail1, cookieOptions);
					if (!Request.Cookies.ContainsKey("Billing.Invoice.Exchange-Rate-Date"))
					{
						Response.Cookies.Append("Billing.Invoice.Exchange-Rate-Date", DateTime.Now.ToString("yyyy-MM-dd HH:mm"), cookieOptions);
					}
				}
			}
			else
			{
				if (!string.IsNullOrWhiteSpace(viewModel.Invoice?.Detail1))
				{
					Response.Cookies.Append("Billing.Invoice.Exchange-Rate", viewModel.Invoice.Detail1, cookieOptions);
					Response.Cookies.Append("Billing.Invoice.Exchange-Rate-Date", DateTime.Now.ToString("yyyy-MM-dd HH:mm"), cookieOptions);
				}
			}
			if (Request.Cookies.ContainsKey("Billing.Invoice.Operator-Details"))
			{
				if (viewModel.Invoice?.Detail2 != Request.Cookies["Billing.Invoice.Operator-Details"])
				{
                    if (string.IsNullOrWhiteSpace(viewModel.Invoice?.Detail2)) Response.Cookies.Delete("Billing.Invoice.Operator-Details");
                    else Response.Cookies.Append("Billing.Invoice.Operator-Details", viewModel.Invoice.Detail2, cookieOptions);
				}
			}
			else
			{
				if (!string.IsNullOrWhiteSpace(viewModel.Invoice?.Detail2))
				{
					Response.Cookies.Append("Billing.Invoice.Operator-Details", viewModel.Invoice.Detail2, cookieOptions);
				}
			}
			if (Request.Cookies.ContainsKey("Billing.Invoice.Comments"))
			{
				if (viewModel.Invoice?.Detail3 != Request.Cookies["Billing.Invoice.Comments"])
				{
                    if (string.IsNullOrWhiteSpace(viewModel.Invoice?.Detail3)) Response.Cookies.Delete("Billing.Invoice.Comments");
                    else Response.Cookies.Append("Billing.Invoice.Comments", viewModel.Invoice.Detail3, cookieOptions);
				}
			}
			else
			{
				if (!string.IsNullOrWhiteSpace(viewModel.Invoice?.Detail3))
				{
					Response.Cookies.Append("Billing.Invoice.Comments", viewModel.Invoice.Detail3, cookieOptions);
				}
			}
			#endregion
			bool success = false;
			if (viewModel.Invoice != null)
				success = await BeezMart.DAL.Billing.Invoices.SaveAsync(viewModel.Invoice);
			if (success)
			{
				return RedirectToAction("Drafts");
			}
		}
		viewModel.HandoverDelegates = await BeezMart.DAL.Billing.HandoverDelegates.ListAsync();
		viewModel.HandoverTransports = await BeezMart.DAL.Billing.HandoverTransports.ListAsync();
		return View(viewModel);
	}
	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<JsonResult> _SaveFields(InvoiceModel invoice)
	{
		Dictionary<string, object> result = new Dictionary<string, object>();
		TryValidateModel(invoice);
		if (ModelState.IsValid)
		{
			bool success = await BeezMart.DAL.Billing.Invoices.SaveAsync(invoice);
			if (success && invoice.ID != null)
			{
				result.Add("Message", "Invoice successfully saved.");
				result.Add("InvoiceID", invoice.ID);
			}
			else
			{
				result.Add("Message", "ERROR: Invoice could not be properly saved.");
			}
		}
		else
		{
			result.Add("Message", "ERROR: Invoice fields are incomplete or invalid.");
		}
		return Json(result);
	}

	public async Task<ViewResult> Drafts()
	{
		Drafts_ViewModel viewModel = new Drafts_ViewModel();
		string defaultCurrency = MyApp.ConfigSettings["Billing.Default-Currency"];
		viewModel.InvoicesRegular = await BeezMart.DAL.Billing.Invoices.ListFilteredByTypeAndStatusAsync(InvoiceType.Regular, InvoiceStatus.Draft, defaultCurrency);
		viewModel.InvoicesStorno = await BeezMart.DAL.Billing.Invoices.ListFilteredByTypeAndStatusAsync(InvoiceType.Storno, InvoiceStatus.Draft, defaultCurrency);

BeezMart/Areas/Archiving/Views/DocLinks/Activities.cshtml
@using BeezMart.Entities.TimeSheet
@model List<ActivityModel>
@{
	if (Model == null) throw new NullReferenceException("ViewModel is null.");
}
@Html.Raw(ViewBag.AppMessage)
<table class="table table-striped table-hover table-sm">
    <tbody>
        @foreach (ActivityModel activity in Model)
        {
        <tr data-id="@activity.ID">
            <td><a>@activity.Title</a></td>
            <td>@Html.FormatValue(activity.ScheduledStart, "{0:yyyy-MM-dd}")</td>
            <td><a title="Delete"><b class="bi-trash"></b></a></td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">records found: <b>@Model.Count.ToString("#,##0")</b></td>
        </tr>
    </tfoot>
</table>

BeezMart/Areas/Archiving/Views/DocLinks/Documents.cshtml
@model List<DocumentModel>
@{
	if (Model == null) throw new NullReferenceException("ViewModel is null.");
}
@Html.Raw(ViewBag.AppMessage)
<table class="table table-striped table-hover table-sm">
    <tbody>
        @foreach (DocumentModel document in Model)
        {
            <tr>
                <td class="@document.Status"><a>@document.Title</a></td>
                <td>@document.CategoryName</td>
                <td>@document.AddedOn</td>
                <td>@document.DocumentDate</td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">records found: <b>@Model.Count.ToString("#,##0")</b></td>
        </tr>
    </tfoot>
</table>

BeezMart/Areas/Archiving/Views/DocLinks/Invoices.cshtml
@using BeezMart.Entities.Billing
@model List<InvoiceModel>
@{
	if (Model == null) throw new NullReferenceException("ViewModel is null.");
}
@Html.Raw(ViewBag.AppMessage)
<table class="table table-striped table-hover table-sm">
    <tbody>
        @foreach (InvoiceModel invoice in Model)
        {
        <tr data-id="@invoice.ID">
            <td title="@invoice.Status"><a>@Html.FormatValue(invoice.IssueDate, "{0:yyyy-MM-dd}") &bull; @(string.IsNullOrWhiteSpace(invoice.AccountingID) ? "[ID NOT SET]" : invoice.AccountingID)</a></td>
            <td>@invoice.CustomerName</td>
            <td><b>@Html.FormatValue(invoice.TotalDue, "{0:#,##0.00}")</b> @invoice.Currency</td>
            <td><a title="Delete"><b class="bi-trash"></b></a></td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4">records found: <b>@Model.Count.ToString("#,##0")</b></td>
        </tr>
    </tfoot>
</table>

BeezMart/Areas/Archiving/Views/DocLinks/LinkDocuments.cshtml
@using BeezMart.Areas.Archiving.ViewModels.Files;
@model BeezMart.Areas.Archiving.ViewModels.Files.Index_ViewModel
@{
    if (Model == null || Model.FileNames == null) throw new NullReferenceException("ViewModel is null or ViewModel.FileNames is null.");
}
@Html.Raw(ViewBag.AppMessage)
<table class="table table-striped table-hover table-sm">
    <tbody>
        @foreach (string fileName in Model.FileNames)
        {
            <tr data-id="@System.Net.WebUtility.UrlEncode(fileName)">
                <td><i class="@FileIcons.GetClassNameForFileName(fileName)"></i></td>
                <td><a>@System.Net.WebUtility.UrlDecode(fileName)</a></td>
                <td>
                    <a title="Rename"><b class="bi-pencil-square"></b></a>
                    <a title="Delete"><b class="bi-trash"></b></a>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">files found: <b>@Model.FileNames.Count().ToString("#,##0")</b></td>
        </tr>
    </tfoot>
</table>

BeezMart/Areas/Archiving/Views/DocLinks/LinkInvoices.cshtml
@using BeezMart.Entities.Billing
@using BeezMart
@model BeezMart.Areas.Archiving.ViewModels.DocLinks.LinkInvoices_ViewModel

@{
	ViewBag.Title = "Lookup invoices to link";
	string DefaultCurrency = MyApp.ConfigSettings["Billing.Default-Currency"];
	if (Model == null || Model.Document == null) throw new NullReferenceException("ViewModel is null or ViewModel.Document is null.");
}

@section head {
	<link rel="stylesheet" href="~/Areas/Archiving/DocLinks/LinkInvoices.css" />
}

@section breadcrumb {
		<li class="breadcrumb-item"><a asp-area="Archiving" asp-controller="Home" asp-action="Index">Archiving</a></li>
		<li class="breadcrumb-item"><a asp-area="Archiving" asp-controller="Documents" asp-action="Index">Documents</a></li>
		<li class="breadcrumb-item"><a asp-area="Archiving" asp-controller="Documents" asp-action="View" asp-route-ID="@Model.Document.ID">@Model.Document.Title</a></li>
		<li class="breadcrumb-item active">link invoices</li>
}

@Html.Raw(ViewBag.AppMessage)
<div id="ChangeFilter">
	<button onclick="javascript: btnChangeFilter_Click();" type="button" class="btn btn-primary">Search again: change filter</button>
</div>
<section id="SearchForm">
	<form asp-action="_LinkInvoices" method="get">
		<fieldset class="card">
			<h2 class="card-header">Link invoices...</h2>
			<div class="card-body">
				<div class="row">
					<div class="mb-3 col-12 col-sm-6 col-lg-8">
						<label asp-for="@Model.Customer">Customer name like...</label>
						<div class="input-group">
							<input type="text" asp-for="@Model.Customer" maxlength="256" placeholder="Name filter pattern" class="form-control" />
							<span class="input-group-text" title="Exact match&#13;When checked, search will not append and prepend * wildcard to customer name criteria" style="cursor:help;">
								<input type="checkbox" asp-for="@Model.Exact" />
							</span>
						</div>
					</div>
					<div class="mb-3 col-6 col-sm-3 col-lg-2">
						<label asp-for="@Model.After">Issued after</label>
						<div class="input-group">
							<input type="text" asp-for="@Model.After" asp-format="{0:yyyy-MM-dd}" maxlength="16" placeholder="yyyy-mm-dd" class="form-control Calendar" />
							<span class="input-group-text Calendar"><b class="bi-calendar3"></b></span>
						</div>
					</div>
					<div class="mb-3 col-6 col-sm-3 col-lg-2">
						<label asp-for="@Model.Before">Issued before</label>
						<div class="input-group">
							<input type="text" asp-for="@Model.Before" asp-format="{0:yyyy-MM-dd}" maxlength="16" placeholder="yyyy-mm-dd" class="form-control Calendar" />
							<span class="input-group-text Calendar"><b class="bi-calendar3"></b></span>
						</div>
					</div>
				</div>
				<div id="AdvancedSearch">
					<div class="mb-3">
						<label asp-for="@Model.IDs">Search by Invoice ID references</label>
						<input type="text" asp-for="@Model.IDs" maxlength="1024" placeholder="Comma-separated IDs from database; negative or positive integer numbers" class="form-control" />
					</div>
					<div class="mb-3">
						<label asp-for="@Model.AccIDs">Search by Accounting No references</label>
						<input type="text" asp-for="@Model.AccIDs" maxlength="1024" placeholder="Semicolon-separated IDs as printed on invoices; strings with serials" class="form-control" />
					</div>
					<div class="row">
						<div class="mb-3 col-sm-4">
							<label asp-for="@Model.Curr">Currency</label>
							<input type="text" asp-for="@Model.Curr" maxlength="3" placeholder="Ex: @DefaultCurrency" class="form-control" />
						</div>
						<div class="mb-3 col-sm-8">
							<label>Invoice status</label>
							<select name="Status" data-selected="@Model.Status" class="form-control">
								<option value="" selected="selected">=== SELECT TO FILTER BY STATUS ===</option>
								<option value="@InvoiceStatus.Draft">DRAFT, still working on it</option>
								<option value="@InvoiceStatus.Validated">VALIDATED, ready to print and send</option>
								<option value="@InvoiceStatus.SentToCustomer">PENDING, sent to customer</option>
								<option value="@InvoiceStatus.Cancelled">CANCELLED, null and void</option>
								<option value="@InvoiceStatus.Closed">CLOSED, paid and archived</option>
							</select>
						</div>
					</div>
				</div>
			</div>
			<div class="card-footer">
				<div class="row">
					<div class="col-6" id="btnAdvancedSearch"><a>Advanced search</a></div>
					<div class="col-6 Submit"><button type="submit" class="btn btn-success pull-right">Search invoices</button></div>
				</div>
			</div>
		</fieldset>
	</form>
</section>
<form asp-action="Link" method="POST">
	<progress></progress>
	<section id="SearchResults">

	</section>
	<input type="hidden" name="ReturnUrl" value="@Url.Action("View", "Documents", new { ID=Model.Document.ID})" />
	<input type="hidden" name="EntityType" value="@Model.EntityType" />
	<input type="hidden" name="DocumentID" value="@Model.Document.ID" />
	<div class="Submit">
		<button type="submit" class="btn btn-primary">Link selected</button>
	</div>
</form>
<section id="Legend">
	<p>Invoice status:
		@*
		<label class="InvoiceStatus Draft"><i class="bi-list-task"></span> Draft</label>
		<label class="InvoiceStatus Validated"><i class="bi-list-task"></span> Validated</label>
		<label class="InvoiceStatus SentToCustomer"><i class="bi-list-task"></span> SentToCustomer</label>
		<label class="InvoiceStatus Closed"><i class="bi-list-task"></span> Closed</label>
		<label class="InvoiceStatus Cancelled"><i class="bi-list-task"></span> Cancelled</label>
		*@
		<label class="InvoiceStatus text-primary"><i class="bi-list-task"></i> Draft</label>
		<label class="InvoiceStatus text-info"><i class="bi-list-task"></i> Validated</label>
		<label class="InvoiceStatus text-warning"><i class="bi-list-task"></i> SentToCustomer</label>
		<label class="InvoiceStatus text-success"><i class="bi-list-task"></i> Closed</label>
		<label class="InvoiceStatus text-secondary"><i class="bi-list-task"></i> Cancelled</label>
	</p>
</section>
<input type="hidden" id="hdnBillingInvoicesViewUrl" value="@Url.Action("View", "Invoices", new { Area="Billing", InvoiceID="" })" />
<input type="hidden" id="hdnCrmOrgsViewUrl" value="@Url.Action("View", "Organizations", new { Area="CRM", OrganizationID="" })" />
<input type="hidden" id="hdnCrmPersViewUrl" value="@Url.Action("View", "Persons", new { Area="CRM", PersonID="" })" />

@section scripts {
	<script type="text/javascript" src="~/Areas/Archiving/DocLinks/LinkInvoices.js"></script>
}