BeezMart/Areas/CRM/Controllers/OrgActivitiesController.cs
using BeezMart.Areas.CRM.ViewModels.OrgActivities;
using BeezMart.Entities.CRM;
using BeezMart.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BeezMart.Areas.CRM.Controllers;

[Area("CRM")]
[Authorize(Roles = BeezMart.Security.UserRoles.UserForCRM)]
public class OrgActivitiesController : Controller
{
    public async Task<ViewResult> Index(int OrganizationID)
    {
        Index_ViewModel viewModel = new Index_ViewModel { };
        viewModel.Organization = await BeezMart.DAL.CRM.Organizations.RetrieveAsync(OrganizationID);
        viewModel.Activities = await BeezMart.DAL.CRM.OrgActivities.ListAsync(OrganizationID);
        return View(viewModel);
    }
    public async Task<PartialViewResult> _Index(int OrganizationID)
    {
        List<OrgActivityModel> viewModel = await BeezMart.DAL.CRM.OrgActivities.ListAsync(OrganizationID);
        ViewBag.OrganizationID = OrganizationID;
        return PartialView(viewModel);
    }

    [HttpGet]
    public async Task<ViewResult> Edit(long ActivityID)
    {
        Edit_ViewModel viewModel = new Edit_ViewModel();
        viewModel.Activity = await BeezMart.DAL.CRM.OrgActivities.RetrieveAsync(ActivityID);
        if (viewModel.Activity == null)
        {
            AppMessage msg = new AppMessage();
            msg.AppendMessage($"The activity record you're trying to edit no longer exist in the database. ActivityID = {ActivityID}.");
            ViewBag.AppMessage = msg.ToHtmlError();
            return View("Message");
        }
        viewModel.Organization = await BeezMart.DAL.CRM.Organizations.RetrieveAsync(viewModel.Activity.OrganizationID);
        return View(viewModel);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Edit(Edit_ViewModel viewModel)
    {
        if (viewModel.Activity == null) throw new NullReferenceException("Model binding has resulted in a null ViewModel.Activity.");
        bool success = await BeezMart.DAL.CRM.OrgActivities.SaveAsync(viewModel.Activity);
        if (success)
        {
            return RedirectToAction("View", "Organizations", new { OrganizationID = viewModel.Activity.OrganizationID, tab = 4 });
        }
        else
        {
            AppMessage msg = new AppMessage();
            msg.AppendMessage("You have submitted an invalid or incomplete activity record. Please check and try again.");
            ViewBag.AppMessage = msg.ToHtmlError();
            return View(viewModel);
        }
    }

    [HttpGet]
    public async Task<ViewResult> Add(int OrganizationID)
    {
        Add_ViewModel viewModel = new Add_ViewModel();
        viewModel.Organization = await BeezMart.DAL.CRM.Organizations.RetrieveAsync(OrganizationID);
        if (viewModel.Organization == null)
        {
            AppMessage msg = new AppMessage();
            msg.AppendMessage($"The organization record no longer exist in the database. OrganizationID = {OrganizationID}.");
            ViewBag.AppMessage = msg.ToHtmlError();
            return View("Message");
        }
        if (viewModel.Organization.ID == null) throw new NullReferenceException("After retrieving the record from database, its identifier is missing: Organization.ID is null.");
        viewModel.Activity = new OrgActivityModel();
        viewModel.Activity.OrganizationID = viewModel.Organization.ID.Value;
        return View(viewModel);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Add(Add_ViewModel viewModel)
    {
        if (viewModel.Activity == null) throw new NullReferenceException("Model binding has resulted in a null ViewModel.Activity.");
        bool success = await BeezMart.DAL.CRM.OrgActivities.SaveAsync(viewModel.Activity);
        if (success)
        {
            return RedirectToAction("View", "Organizations", new { OrganizationID = viewModel.Activity.OrganizationID, tab = 4 });
        }
        else
        {
            AppMessage msg = new AppMessage();
            msg.AppendMessage("You have submitted an invalid or incomplete activity record. Please check and try again.");
            ViewBag.AppMessage = msg.ToHtmlError();
            return View(viewModel);
        }
    }

    [HttpDelete]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Delete(int OrganizationID, long ActivityID)
    {
        await BeezMart.DAL.CRM.OrgActivities.DeleteAsync(ActivityID);
        return RedirectToAction("View", "Organizations", new { OrganizationID = OrganizationID, tab = 4 });
    }
}

BeezMart/Areas/CRM/Views/OrgActivities/Add.cshtml
@using BeezMart.Caching.CRM
@model BeezMart.Areas.CRM.ViewModels.OrgActivities.Add_ViewModel

@{
	ViewBag.Title = "Add organization activity";
	if (Model == null) throw new NullReferenceException("ViewModel. is null.");
	if (Model.Organization == null) throw new NullReferenceException("ViewModel.Organization is null.");
	if (Model.Activity == null) throw new NullReferenceException("ViewModel.Activity is null.");
	IEnumerable<string> categories = await OrgActivities.GetCategoriesAsync();
	IEnumerable<OrgActivityModel.ActivityTypeModel> activityTypes = await OrgActivities.GetActivityTypesAsync();
}

@section head {
	<link rel="stylesheet" href="~/Areas/CRM/OrgActivities/Add.css" />
}

@section breadcrumb {
	<li class="breadcrumb-item"><a asp-area="CRM" asp-controller="Home" asp-action="Index">CRM</a></li>
	<li class="breadcrumb-item"><a asp-area="CRM" asp-controller="Organizations" asp-action="Index">Organizations</a></li>
	<li class="breadcrumb-item"><a asp-area="CRM" asp-controller="Organizations" asp-action="View" asp-route-OrganizationID="@Model.Organization.ID" asp-route-tab="4">@Model.Organization.Name</a></li>
	<li class="breadcrumb-item"><a asp-area="CRM" asp-controller="OrgActivities" asp-action="Index" asp-route-OrganizationID="@Model.Organization.ID">Activities</a></li>
	<li class="breadcrumb-item active">add new</li>
}

@Html.Raw(ViewBag.AppMessage)
<form asp-action="Add" method="post">
	<input type="hidden" name="Activity.ID" value="@Model.Activity.ID" />
	<input type="hidden" name="Activity.OrganizationID" value="@Model.Activity.OrganizationID" />
	<input type="hidden" name="Activity.InvoiceIDs" value="@Model.Activity.InvoiceIDs" />
	<div class="row">
		<div class="col-sm-12 mb-3">
			<label>Title</label>
			<input type="text" name="Activity.Title" value="@Model.Activity.Title" maxlength="1024" required="required" placeholder="Subject, or a brief for reference" class="form-control form-control-lg required" />
		</div>
		<div class="col-sm-4 mb-3">
			<label>Category</label>
			<select id="ddlActivityCategory" class="form-control">
				<option selected="selected" value="">=== NO CATEGORY ===</option>
				@foreach (string category in categories)
				{
					<option>@category</option>
				}
			</select>
		</div>
		<div class="col-sm-4 mb-3">
			<label>Activity type</label>
			<select id="ddlActivityType" name="Activity.TypeID" data-val="@Model.Activity.TypeID" class="form-control">
				<option selected="selected">=== PLEASE SELECT ===</option>
				@foreach (OrgActivityModel.ActivityTypeModel activityType in activityTypes)
				{
					<option data-val-category="@activityType.Category" value="@activityType.ID">@activityType.Name</option>
				}
			</select>
		</div>
		<div class="col-sm-4 mb-3">
			<label>Status</label>
			<select id="ddlActivityStatus" name="Activity.Status" data-val="@Model.Activity.Status" class="form-control">
				<option value="10">Pending</option>
				<option value="20">Cancelled</option>
				<option value="50">In progress</option>
				<option value="51">In progress 1%</option>
				<option value="52">In progress 5%</option>
				<option value="53">In progress 10%</option>
				<option value="54">In progress 15%</option>
				<option value="55">In progress 20%</option>
				<option value="56">In progress 25%</option>
				<option value="57">In progress 30%</option>
				<option value="58">In progress 35%</option>
				<option value="59">In progress 40%</option>
				<option value="60">In progress 45%</option>
				<option value="61">In progress 50%</option>
				<option value="62">In progress 55%</option>
				<option value="63">In progress 60%</option>
				<option value="64">In progress 65%</option>
				<option value="65">In progress 70%</option>
				<option value="66">In progress 75%</option>
				<option value="67">In progress 80%</option>
				<option value="68">In progress 85%</option>
				<option value="69">In progress 90%</option>
				<option value="70">In progress 95%</option>
				<option value="71">In progress 99%</option>
				<option value="250">Completed</option>
			</select>
		</div>
		<div class="col-sm-12 mb-3">
			<label>Comments about status</label>
			<textarea name="Activity.StatusComment" cols="80" rows="5" placeholder="Explanation about the status, if needed" maxlength="256" class="form-control">@Html.Raw(Model.Activity.StatusComment)</textarea>
		</div>
		<div class="col-sm-12 mb-3">
			<label>Detailed info about activity</label>
			<textarea name="Activity.Details" cols="80" rows="24" placeholder="You may add full details about the activity here" class="form-control">@Html.Raw(Model.Activity.Details)</textarea>
		</div>
		<div class="col-6 col-md-3 mb-3">
			<label>Scheduled for</label>
			<div class="input-group">
				<input type="text" asp-for="@Model.Activity.ScheduledFor" asp-format="{0:yyyy-MM-dd}" maxlength="16" placeholder="yyyy-mm-dd" class="form-control Calendar" />
				<span class="input-group-text Calendar"><b class="bi-calendar3"></b></span>
			</div>
		</div>
		<div class="col-6 col-md-3 mb-3">
			<label>Reminder on...</label>
			<div class="input-group">
				<input type="text" asp-for="@Model.Activity.ReminderOn" asp-format="{0:yyyy-MM-dd}" maxlength="16" placeholder="yyyy-mm-dd" class="form-control Calendar" />
				<span class="input-group-text Calendar"><b class="bi-calendar3"></b></span>
			</div>
		</div>
		<div class="col-6 col-md-3 mb-3">
			<label>Started on...</label>
			<div class="input-group">
				<input type="text" asp-for="@Model.Activity.StartedOn" asp-format="{0:yyyy-MM-dd}" maxlength="16" placeholder="yyyy-mm-dd" class="form-control Calendar" />
				<span class="input-group-text Calendar"><b class="bi-calendar3"></b></span>
			</div>
		</div>
		<div class="col-6 col-md-3 mb-3">
			<label>Completed on...</label>
			<div class="input-group">
				<input type="text" asp-for="@Model.Activity.CompletedOn" asp-format="{0:yyyy-MM-dd}" maxlength="16" placeholder="yyyy-mm-dd" class="form-control Calendar" />
				<span class="input-group-text Calendar"><b class="bi-calendar3"></b></span>
			</div>
		</div>
		<div class="col-12 col-md-6 mb-3">
			<label>Requested by</label>
			<input type="text" name="Activity.RequestedBy" value="@Model.Activity.RequestedBy" maxlength="128" placeholder="Name (department, company...)" class="form-control" />
		</div>
		<div class="col-12 col-md-6 mb-3">
			<label>Completed by</label>
			<input type="text" name="Activity.CompletedBy" value="@Model.Activity.CompletedBy" maxlength="128" placeholder="Name (department, company...)" class="form-control" />
		</div>
		<div class="col-6 col-md-4 col-lg-3 mb-3">
			<label>Duration in minutes</label>
			<input type="text" name="Activity.DurationInMinutes" value="@Model.Activity.DurationInMinutes" maxlength="16" placeholder="Integer number here" class="form-control" />
		</div>
		<div class="col-6 col-md-8 col-lg-9 mb-3">
			<label>Billable activity?</label>
			<label class="input-group">
				<span class="input-group-text"><input type="checkbox" asp-for="@Model.Activity.IsBillable" /></span>
				<span class="form-control">Should be invoiced</span>
			</label>
		</div>
	</div>
	<div class="mt-3 submit">
		<a asp-action="View" asp-controller="Organizations" asp-route-OrganizationID="@Model.Organization.ID" asp-route-tab="4" class="btn btn-light">Cancel</a>
		<button type="submit" class="btn btn-primary">Save activity record</button>
	</div>
</form>

@section scripts {
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.10.9/tinymce.min.js"></script>
	<script type="text/javascript" src="~/Areas/CRM/OrgActivities/Add.js"></script>
}

BeezMart/Areas/CRM/Views/OrgActivities/Edit.cshtml
@using BeezMart.Caching.CRM
@model BeezMart.Areas.CRM.ViewModels.OrgActivities.Edit_ViewModel

@{
	ViewBag.Title = "Edit organization activity";
	if (Model == null) throw new NullReferenceException("ViewModel. is null.");
	if (Model.Organization == null) throw new NullReferenceException("ViewModel.Organization is null.");
	if (Model.Activity == null) throw new NullReferenceException("ViewModel.Activity is null.");
	IEnumerable<string> categories = await OrgActivities.GetCategoriesAsync();
	IEnumerable<OrgActivityModel.ActivityTypeModel> activityTypes = await OrgActivities.GetActivityTypesAsync();
}

@section head {
	<link rel="stylesheet" href="~/Areas/CRM/OrgActivities/Edit.css" />
}

@section breadcrumb {
	<li class="breadcrumb-item"><a asp-area="CRM" asp-controller="Home" asp-action="Index">CRM</a></li>
	<li class="breadcrumb-item"><a asp-area="CRM" asp-controller="Organizations" asp-action="Index">Organizations</a></li>
	<li class="breadcrumb-item"><a asp-area="CRM" asp-controller="Organizations" asp-action="View" asp-route-OrganizationID="@Model.Organization.ID" asp-route-tab="4">@Model.Organization.Name</a></li>
    <li class="breadcrumb-item"><a asp-area="CRM" asp-controller="OrgActivities" asp-action="Index" asp-route-OrganizationID="@Model.Organization.ID">Activities</a></li>
	<li class="breadcrumb-item active">edit</li>
}

@Html.Raw(ViewBag.AppMessage)
<form asp-action="Edit" method="post">
	<input type="hidden" name="Activity.ID" value="@Model.Activity.ID" />
	<input type="hidden" name="Activity.OrganizationID" value="@Model.Activity.OrganizationID" />
	<input type="hidden" name="Activity.InvoiceIDs" value="@Model.Activity.InvoiceIDs" />
	<div class="row">
		<div class="col-sm-12 mb-3">
			<label>Title</label>
			<input type="text" name="Activity.Title" value="@Model.Activity.Title" maxlength="1024" required="required" placeholder="Subject, or a brief for reference" class="form-control form-control-lg required" />
		</div>
		<div class="col-sm-4 mb-3">
			<label>Category</label>
			<select id="ddlActivityCategory" class="form-control">
				<option selected="selected" value="">=== NO CATEGORY ===</option>
				@foreach (string category in categories)
				{
					<option>@category</option>
				}
			</select>
		</div>
		<div class="col-sm-4 mb-3">
			<label>Activity type</label>
			<select id="ddlActivityType" name="Activity.TypeID" data-val="@Model.Activity.TypeID" class="form-control">
				<option selected="selected">=== PLEASE SELECT ===</option>
				@foreach (OrgActivityModel.ActivityTypeModel activityType in activityTypes)
				{
					<option data-val-category="@activityType.Category" value="@activityType.ID">@activityType.Name</option>
				}
			</select>
		</div>
		<div class="col-sm-4 mb-3">
			<label>Status</label>
			<select id="ddlActivityStatus" name="Activity.Status" data-val="@Model.Activity.Status" class="form-control">
				<option value="10">Pending</option>
				<option value="20">Cancelled</option>
				<option value="50">In progress</option>
				<option value="51">In progress 1%</option>
				<option value="52">In progress 5%</option>
				<option value="53">In progress 10%</option>
				<option value="54">In progress 15%</option>
				<option value="55">In progress 20%</option>
				<option value="56">In progress 25%</option>
				<option value="57">In progress 30%</option>
				<option value="58">In progress 35%</option>
				<option value="59">In progress 40%</option>
				<option value="60">In progress 45%</option>
				<option value="61">In progress 50%</option>
				<option value="62">In progress 55%</option>
				<option value="63">In progress 60%</option>
				<option value="64">In progress 65%</option>
				<option value="65">In progress 70%</option>
				<option value="66">In progress 75%</option>
				<option value="67">In progress 80%</option>
				<option value="68">In progress 85%</option>
				<option value="69">In progress 90%</option>
				<option value="70">In progress 95%</option>
				<option value="71">In progress 99%</option>
				<option value="250">Completed</option>
			</select>
		</div>
		<div class="col-sm-12 mb-3">
			<label>Comments about status</label>
			<textarea name="Activity.StatusComment" cols="80" rows="5" placeholder="Explanation about the status, if needed" maxlength="256" class="form-control">@Html.Raw(Model.Activity.StatusComment)</textarea>
		</div>
		<div class="col-sm-12 mb-3">
			<label>Detailed info about activity</label>
			<textarea name="Activity.Details" cols="80" rows="24" placeholder="You may add full details about the activity here" class="form-control">@Html.Raw(Model.Activity.Details)</textarea>
		</div>
		<div class="col-6 col-md-3 mb-3">
			<label>Scheduled for</label>
			<div class="input-group">
				<input type="text" asp-for="@Model.Activity.ScheduledFor" asp-format="{0:yyyy-MM-dd}" maxlength="16" placeholder="yyyy-mm-dd" class="form-control Calendar" />
				<span class="input-group-text Calendar"><b class="bi-calendar3"></b></span>
			</div>
		</div>
		<div class="col-6 col-md-3 mb-3">
			<label>Reminder on...</label>
			<div class="input-group">
				<input type="text" asp-for="@Model.Activity.ReminderOn" asp-format="{0:yyyy-MM-dd}" maxlength="16" placeholder="yyyy-mm-dd" class="form-control Calendar" />
				<span class="input-group-text Calendar"><b class="bi-calendar3"></b></span>
			</div>
		</div>
		<div class="col-6 col-md-3 mb-3">
			<label>Started on...</label>
			<div class="input-group">
				<input type="text" asp-for="@Model.Activity.StartedOn" asp-format="{0:yyyy-MM-dd}" maxlength="16" placeholder="yyyy-mm-dd" class="form-control Calendar" />
				<span class="input-group-text Calendar"><b class="bi-calendar3"></b></span>
			</div>
		</div>
		<div class="col-6 col-md-3 mb-3">
			<label>Completed on...</label>
			<div class="input-group">
				<input type="text" asp-for="@Model.Activity.CompletedOn" asp-format="{0:yyyy-MM-dd}" maxlength="16" placeholder="yyyy-mm-dd" class="form-control Calendar" />
				<span class="input-group-text Calendar"><b class="bi-calendar3"></b></span>
			</div>
		</div>
		<div class="col-12 col-md-6 mb-3">
			<label>Requested by</label>
			<input type="text" name="Activity.RequestedBy" value="@Model.Activity.RequestedBy" maxlength="128" placeholder="Name (department, company...)" class="form-control" />
		</div>
		<div class="col-12 col-md-6 mb-3">
			<label>Completed by</label>
			<input type="text" name="Activity.CompletedBy" value="@Model.Activity.CompletedBy" maxlength="128" placeholder="Name (department, company...)" class="form-control" />
		</div>
		<div class="col-6 col-md-4 col-lg-3 mb-3">
			<label>Duration in minutes</label>
			<input type="text" name="Activity.DurationInMinutes" value="@Model.Activity.DurationInMinutes" maxlength="16" placeholder="Integer number here" class="form-control" />
		</div>
		<div class="col-6 col-md-8 col-lg-9 mb-3">
			<label>Billable activity?</label>
			<label class="input-group">
				<span class="input-group-text"><input type="checkbox" asp-for="@Model.Activity.IsBillable" /></span>
				<span class="form-control">Should be invoiced</span>
			</label>
		</div>
	</div>
	<div class="mt-3 submit">
		<a asp-action="View" asp-controller="Organizations" asp-route-OrganizationID="@Model.Organization.ID" asp-route-tab="4" class="btn btn-light">Cancel</a>
		<button type="submit" class="btn btn-primary">Save activity record</button>
	</div>
</form>

@section scripts {
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.10.9/tinymce.min.js"></script>
	<script type="text/javascript" src="~/Areas/CRM/OrgActivities/Edit.js"></script>
}

BeezMart/Areas/CRM/Views/OrgActivities/Index.cshtml
@model BeezMart.Areas.CRM.ViewModels.OrgActivities.Index_ViewModel

@{
	ViewBag.Title = "Organization activities";
	if (Model == null) throw new NullReferenceException("ViewModel. is null.");
	if (Model.Organization == null) throw new NullReferenceException("ViewModel.Organization is null.");
	if (Model.Activities == null) throw new NullReferenceException("ViewModel.Activities is null.");
}

@section breadcrumb {
    <li class="breadcrumb-item"><a asp-area="CRM" asp-controller="Home" asp-action="Index">CRM</a></li>
    <li class="breadcrumb-item"><a asp-area="CRM" asp-controller="Organizations" asp-action="Index">Organizations</a></li>
    <li class="breadcrumb-item"><a asp-area="CRM" asp-controller="Organizations" asp-action="View" asp-route-OrganizationID="@Model.Organization.ID" asp-route-tab="4">@Model.Organization.Name</a></li>
    <li class="breadcrumb-item active">Activities</li>
}

@Html.Raw(ViewBag.AppMessage)
<table class="table table-hover table-striped table-responsive-md">
	<thead>
		<tr>
			<th colspan="2">Related activities</th>
		</tr>
	</thead>
	<tbody>
		@foreach (OrgActivityModel activity in Model.Activities)
		{
			<tr data-record="@activity.ID">
				<td><a>@activity.Title</a></td>
				<td>(status)</td>
			</tr>
		}
	</tbody>
	<tfoot>
		<tr>
			<td><a asp-action="Add" asp-route-OrganizationID="@Model.Organization.ID" class="btn btn-primary">Add new activity record</a></td>
		</tr>
	</tfoot>
</table>

BeezMart/Areas/CRM/Views/OrgActivities/_Index.cshtml
@model List<OrgActivityModel>
@{
	if (Model == null) throw new NullReferenceException("ViewModel is null.");
	int maxRows = 25;
	int rowsCount = 0;
}
@Html.Raw(ViewBag.AppMessage)
<table class="table table-hover table-striped table-responsive-md">
	<thead>
		<tr>
			<th colspan="2">Related activities</th>
		</tr>
	</thead>
	<tbody>
		@foreach (OrgActivityModel activity in Model) {
			rowsCount++;
			if (rowsCount > maxRows) { break; }
			<tr data-record="@activity.ID">
				<td><a>@activity.Title</a></td>
				<td>@activity.Status</td>
			</tr>
		}
	</tbody>
	<tfoot>
		<tr>
			<td>
				@if (Model.Count > maxRows) {
					<a asp-action="Index" asp-route-OrganizationID="@ViewBag.OrganizationID">View more activities</a>
				}
			</td>
			<td><a asp-action="Add" asp-route-OrganizationID="@ViewBag.OrganizationID" class="btn btn-outline-secondary btn-sm">Add new activity record</a></td>
		</tr>
	</tfoot>
</table>