BeezMart/Areas/CRM/Controllers/OrgIntegersController.cs
using BeezMart.Entities.CRM;
using BeezMart.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BeezMart.Areas.CRM.Controllers;

[Area("CRM")]
[Authorize(Roles = BeezMart.Security.UserRoles.UserForCRM)]
public class OrgIntegersController : Controller
{

    public ViewComponentResult _List(int OrganizationID)
    {
        return ViewComponent(typeof(BeezMart.Areas.CRM.ViewComponents.OrgIntegers.List), new { OrganizationID = OrganizationID });
    }

    [HttpGet]
    public ViewComponentResult _Edit(int OrganizationID, long? RecordID)
    {
        return ViewComponent(typeof(BeezMart.Areas.CRM.ViewComponents.OrgIntegers.Edit), new { OrganizationID = OrganizationID, RecordID = RecordID });
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<PartialViewResult> _Edit(OrgIntegerModel integerField)
    {
        List<OrgIntegerModel> viewModel;
        if (!Request.Form.ContainsKey("FieldID") || string.IsNullOrEmpty(Request.Form["FieldID"][0]))
        {
            AppMessage msg = new AppMessage();
            msg.AppendMessage("Please select the type of organization figure you want added!");
            ViewBag.AppMessage = msg.ToHtmlError();
            viewModel = await BeezMart.DAL.CRM.OrgIntegers.ListAsync(integerField.OrganizationID);
            return PartialView("_List", viewModel);
        }
        if (ModelState.IsValid)
        {
            await BeezMart.DAL.CRM.OrgIntegers.SaveAsync(integerField);
        }
        else
        {
            AppMessage msg = new AppMessage();
            msg.AppendMessage("You have submitted an invalid or incomplete organization figure record. Please check and try again.");
            ViewBag.AppMessage = msg.ToHtmlError();
        }
        viewModel = await BeezMart.DAL.CRM.OrgIntegers.ListAsync(integerField.OrganizationID);
        return PartialView("_List", viewModel);
    }

    [HttpDelete]
    [ValidateAntiForgeryToken]
    public async Task<PartialViewResult> _Delete(int OrganizationID, long RecordID)
    {
        await BeezMart.DAL.CRM.OrgIntegers.DeleteAsync(RecordID);
        List<OrgIntegerModel> viewModel = await BeezMart.DAL.CRM.OrgIntegers.ListAsync(OrganizationID);
        return PartialView("_List", viewModel);
    }
}

BeezMart/Areas/CRM/Views/OrgIntegers/_Edit.cshtml
@using BeezMart.Caching.CRM
@model OrgIntegerModel
@{
	if (Model == null) throw new NullReferenceException("ViewModel is null.");
	IEnumerable<string> categories = await OrgIntegers.GetCategoriesAsync();
	IEnumerable<OrgFieldModel> figureTypes = await OrgIntegers.GetFieldTypesAsync();
}
@Html.Raw(ViewBag.AppMessage)
<aside id="ModalEditInteger" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" data-bs-backdrop="static">
	<div class="modal-dialog">
		<div class="modal-content">
			<form asp-action="_Edit" asp-controller="OrgIntegers" method="post" id="frmIntegerDetail">
				<header class="modal-header">
					<h4 class="modal-title">Figure attribute detail</h4>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</header>
				<section class="modal-body">
					<input type="hidden" name="ID" />
					<input type="hidden" name="OrganizationID" value="@Model.OrganizationID" />
					<div class="mb-3">
						<label for="ddlIntegerCategory" class="Required">Category</label>
						<select id="ddlIntegerCategory" onchange="javascript: ddlCategory_Change(this, 'IntegerList');" class="form-control">
							<option selected="selected">=== FIGURES WITH NO CATEGORY ===</option>
							@foreach (string category in categories) {
								<option>@category</option>
							}
						</select>
					</div>
					<div class="mb-3">
						<p>Please select the figure attribute you want to add</p>
						<ul id="IntegerList">
							@foreach (OrgFieldModel figureType in figureTypes) {
								<li data-val-category="@figureType.Category"><label><input type="radio" name="FieldID" value="@figureType.ID" /> @figureType.Name</label></li>
							}
						</ul>
					</div>
					<div class="mb-3">
						<label for="txtIntegerValue">Figure attribute value</label>
						<input type="text" id="txtIntegerValue" name="Value" maxlength="16" value="@Model.Value" class="form-control" />
					</div>
				</section>
				<footer class="modal-footer">
					<button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button>
					<button type="submit" class="btn btn-primary">Save figure</button>
				</footer>
			</form>
		</div>
	</div>
</aside>

BeezMart/Areas/CRM/Views/OrgIntegers/_List.cshtml
@model List<OrgIntegerModel>
@{
	if (Model == null) throw new NullReferenceException("ViewModel is null.");
}
@Html.Raw(ViewBag.AppMessage)
<table class="table table-hover table-sm">
	<thead>
		<tr>
			<th colspan="4">Figure attributes</th>
		</tr>
	</thead>
	<tbody>
		@foreach (OrgIntegerModel record in Model) {
			<tr data-record="@record.ID" data-type="@record.FieldID">
				<td>@record.Category</td>
				<td><a>@record.Name</a></td>
				<td><b>@record.Value.ToString("#,##0")</b></td>
				<td><a>&times;</a></td>
			</tr>
		}
	</tbody>
	<tfoot>
		<tr>
			<td colspan="4"><button type="button" class="btn btn-outline-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#ModalEditInteger">Add new</button></td>
		</tr>
	</tfoot>
</table>